Resources:
  Instance1:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: AMSkey
      ImageId: ami-0fe0b2cf0e1f25c8a
      InstanceType: t2.micro
      Tags:
        - Key: "Name"
          Value: "Example"
      SecurityGroupIds:
        - "!Ref AllowSSH"
  
  AllowSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH Access
      GroupName: Hello
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
      VpcId: vpc-0d4ca5c394c0e2f75